server:
  tomcat:
    uri-encoding: UTF-8
  port: 8090

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_learning_platform?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: dzw042020
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 1
      max-active: 30
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  http:
    encoding:
      force: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: club.doyoudo.platform.model

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  reasonable: true
  params: count=countSql

logging:
  level:
    club.doyoudo.platform: DEBUG
    club.doyoudo.platform.mapper: DEBUG
  file:
    path: logs
